CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(64),
    avatar_url VARCHAR(512),
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_status CHECK (status IN ('active', 'disabled'))
);

CREATE TABLE user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    refresh_token_hash VARCHAR(255) NOT NULL,
    device_info VARCHAR(255),
    ip_address VARCHAR(64),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX idx_user_sessions_refresh_token_hash ON user_sessions(refresh_token_hash);
CREATE INDEX idx_user_sessions_expires_at ON user_sessions(expires_at);

CREATE TABLE uploaded_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    image_url VARCHAR(512) NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    size BIGINT NOT NULL,
    scene VARCHAR(32) NOT NULL DEFAULT 'recognition',
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_uploaded_images_user_created ON uploaded_images(user_id, created_at);

CREATE TABLE recognitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    image_id BIGINT NOT NULL REFERENCES uploaded_images(id),
    category VARCHAR(64) NOT NULL,
    brand VARCHAR(128),
    model VARCHAR(128),
    keywords JSONB NOT NULL DEFAULT '[]'::jsonb,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    suggestion_cards JSONB NOT NULL DEFAULT '[]'::jsonb,
    confidence NUMERIC(5,4) NOT NULL DEFAULT 0,
    ai_provider VARCHAR(32) NOT NULL DEFAULT 'mock',
    fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    explanation TEXT,
    notices JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_recognitions_status CHECK (status IN ('pending', 'succeeded', 'failed')),
    CONSTRAINT ck_recognitions_confidence CHECK (confidence >= 0 AND confidence <= 1)
);
CREATE INDEX idx_recognitions_user_created ON recognitions(user_id, created_at);
CREATE INDEX idx_recognitions_image_id ON recognitions(image_id);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(64) NOT NULL,
    brand VARCHAR(128),
    model VARCHAR(128),
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_brand ON products(brand);

CREATE TABLE platform_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id),
    platform VARCHAR(32) NOT NULL,
    title VARCHAR(512) NOT NULL,
    image_url VARCHAR(512),
    price_amount NUMERIC(12,2) NOT NULL,
    original_price_amount NUMERIC(12,2),
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    url VARCHAR(1024),
    shop_name VARCHAR(255),
    source_type VARCHAR(32) NOT NULL DEFAULT 'mock',
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    sales_volume INTEGER NOT NULL DEFAULT 0,
    rating NUMERIC(3,2),
    is_official BOOLEAN NOT NULL DEFAULT FALSE,
    is_self_operated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_platform_products_platform CHECK (platform IN ('jd', 'taobao', 'pdd', 'tmall', 'other')),
    CONSTRAINT ck_platform_products_source_type CHECK (source_type IN ('mock', 'official_api', 'sample_dataset')),
    CONSTRAINT ck_platform_products_price CHECK (price_amount >= 0),
    CONSTRAINT ck_platform_products_sales_volume CHECK (sales_volume >= 0),
    CONSTRAINT ck_platform_products_rating CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5))
);
CREATE INDEX idx_platform_products_product_id ON platform_products(product_id);
CREATE INDEX idx_platform_products_platform ON platform_products(platform);
CREATE INDEX idx_platform_products_source_type ON platform_products(source_type);

CREATE TABLE price_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_product_id BIGINT NOT NULL REFERENCES platform_products(id),
    price_amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    recorded_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_price_records_price CHECK (price_amount >= 0)
);
CREATE INDEX idx_price_records_product_time ON price_records(platform_product_id, recorded_at);

CREATE TABLE review_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_product_id BIGINT NOT NULL REFERENCES platform_products(id),
    rating NUMERIC(3,2),
    review_count INTEGER,
    positive_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    risk_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    risk_score NUMERIC(5,4) NOT NULL DEFAULT 0,
    summary TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_review_summaries_platform_product UNIQUE (platform_product_id),
    CONSTRAINT ck_review_summaries_rating CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5)),
    CONSTRAINT ck_review_summaries_risk_score CHECK (risk_score >= 0 AND risk_score <= 1)
);

CREATE TABLE search_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    recognition_id BIGINT REFERENCES recognitions(id),
    query TEXT,
    source_type VARCHAR(32) NOT NULL DEFAULT 'mock',
    filters_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    suggestion_cards JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    result_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_search_tasks_source_type CHECK (source_type IN ('mock', 'official_api', 'sample_dataset')),
    CONSTRAINT ck_search_tasks_status CHECK (status IN ('pending', 'succeeded', 'failed')),
    CONSTRAINT ck_search_tasks_result_count CHECK (result_count >= 0)
);
CREATE INDEX idx_search_tasks_user_created ON search_tasks(user_id, created_at);
CREATE INDEX idx_search_tasks_recognition_id ON search_tasks(recognition_id);

CREATE TABLE search_task_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    search_task_id BIGINT NOT NULL REFERENCES search_tasks(id),
    product_id BIGINT REFERENCES products(id),
    platform_product_id BIGINT NOT NULL REFERENCES platform_products(id),
    match_score NUMERIC(5,4) NOT NULL DEFAULT 0,
    match_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    rank_index INTEGER NOT NULL DEFAULT 0,
    source_type VARCHAR(32) NOT NULL DEFAULT 'mock',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_search_task_items_task_product UNIQUE (search_task_id, platform_product_id),
    CONSTRAINT ck_search_task_items_match_score CHECK (match_score >= 0 AND match_score <= 1),
    CONSTRAINT ck_search_task_items_source_type CHECK (source_type IN ('mock', 'official_api', 'sample_dataset'))
);
CREATE INDEX idx_search_task_items_user_task ON search_task_items(user_id, search_task_id);

CREATE TABLE search_task_refinements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    search_task_id BIGINT NOT NULL REFERENCES search_tasks(id),
    user_text TEXT NOT NULL,
    parsed_filters JSONB NOT NULL DEFAULT '{}'::jsonb,
    ai_provider VARCHAR(32) NOT NULL DEFAULT 'rule',
    fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    notices JSONB NOT NULL DEFAULT '[]'::jsonb,
    result_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_search_task_refinements_result_count CHECK (result_count >= 0)
);
CREATE INDEX idx_search_task_refinements_user_task ON search_task_refinements(user_id, search_task_id);

CREATE TABLE comparisons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    search_task_id BIGINT NOT NULL REFERENCES search_tasks(id),
    lowest_platform_product_id BIGINT REFERENCES platform_products(id),
    lowest_price_amount NUMERIC(12,2),
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    platform_stats JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_comparisons_user_created ON comparisons(user_id, created_at);
CREATE INDEX idx_comparisons_search_task ON comparisons(search_task_id);

CREATE TABLE comparison_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    comparison_id BIGINT NOT NULL REFERENCES comparisons(id),
    platform_product_id BIGINT NOT NULL REFERENCES platform_products(id),
    price_amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    match_score NUMERIC(5,4) NOT NULL DEFAULT 0,
    source_type VARCHAR(32) NOT NULL DEFAULT 'mock',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_comparison_items_price CHECK (price_amount >= 0),
    CONSTRAINT ck_comparison_items_match_score CHECK (match_score >= 0 AND match_score <= 1),
    CONSTRAINT ck_comparison_items_source_type CHECK (source_type IN ('mock', 'official_api', 'sample_dataset'))
);
CREATE INDEX idx_comparison_items_user_comparison ON comparison_items(user_id, comparison_id);

CREATE TABLE recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    search_task_id BIGINT NOT NULL REFERENCES search_tasks(id),
    user_query TEXT NOT NULL,
    suggestion VARCHAR(16) NOT NULL,
    recommended_platform_product_id BIGINT REFERENCES platform_products(id),
    reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    risks JSONB NOT NULL DEFAULT '[]'::jsonb,
    output_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_recommendations_suggestion CHECK (suggestion IN ('buy', 'wait', 'avoid', 'compare'))
);
CREATE INDEX idx_recommendations_user_created ON recommendations(user_id, created_at);
CREATE INDEX idx_recommendations_search_task ON recommendations(search_task_id);

CREATE TABLE recommendation_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    recommendation_id BIGINT NOT NULL REFERENCES recommendations(id),
    evidence_type VARCHAR(32) NOT NULL,
    platform_product_id BIGINT REFERENCES platform_products(id),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_recommendation_evidence_type CHECK (evidence_type IN ('price', 'history', 'match', 'review', 'constraint'))
);
CREATE INDEX idx_recommendation_evidence_user_recommendation ON recommendation_evidence(user_id, recommendation_id);

CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    platform_product_id BIGINT NOT NULL REFERENCES platform_products(id),
    note VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_favorites_user_product UNIQUE (user_id, platform_product_id)
);
CREATE INDEX idx_favorites_user_created ON favorites(user_id, created_at);

CREATE TABLE price_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    platform_product_id BIGINT NOT NULL REFERENCES platform_products(id),
    target_price_amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_price_alerts_user_product UNIQUE (user_id, platform_product_id),
    CONSTRAINT ck_price_alerts_target_price CHECK (target_price_amount >= 0)
);
CREATE INDEX idx_price_alerts_user_enabled ON price_alerts(user_id, enabled);
